name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello, actions"
          echo "Test message!!"
      - name: Print goodbye
        run: echo "Actions were executed"
        
